### ISSUE TITLE
'SDImageWebPCoder.h' file not found.

### ISSUE THREAD

**Issue by CaiJingLong** [OpenFlutter/flutter_image_compress#108]
post by im tools of user:

```log
/Users/tian/.pub-cache/hosted/pub.flutter-io.cn/flutter_image_compress-0.6.5/ios/Classes/CompressHandler.m:8:9: error: 'SDImageWebPCoder.h' file not found with <angled> include; use "quotes" instead
    #import <SDImageWebPCoder.h>
            ^~~~~~~~~~~~~~~~~~~~
            "SDImageWebPCoder.h"
    1 error generated.
```

Seem have some problem.

**Comment by CaiJingLong** [comment]
If you have the problem, please use the 0.6.4 version first.

I will resolve it.

**Comment by NEELANSHSETHI** [comment]
Getting the same error, shifting to the previous version resolves it.

**Comment by CaiJingLong** [comment]
I upload the new version 0.6.5+1.
The version fixed the error.

**Comment by dreampiggy** [comment]
Hi. I'm the maintainer of SDWebImage as well as [SDWebImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder).

If you find more issue about SDWebImageWebPCoder, or feature request, you can open a new GitHub issue there so that I can have a track to solve.😂

And currently, because of the exist SDWebImage design, the WebPCoder dependends on the SDWebImage. In the SDWebImage 6.0, the Image Coder and Web Image loading part will be separated. So that it's a clean and standalone framework you can dependent.😼
