### ISSUE TITLE
pod install SYPictureMetadata stuck

### ISSUE THREAD

**Issue by EzekR** [OpenFlutter/flutter_image_compress#66]
when running in debug mode with iOS simulator, android studio ran pod install and stuck. So I cd to project/ios and manually ran "pod install --verbose" and found that process was stuck when git clone https://github.com/dvkch/SYPictureMetadata.git. What's the problem?

**Comment by Tonigt** [comment]
The same problem

**Comment by Tonigt** [comment]
i runing  pod install ,then Failed, and throw error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by CaiJingLong** [comment]
Look like the dvkch/SYPictureMetadata don't be downloaded.

This may be due to the reason that the referenced library is too large, it is 83MB. I will put the target source code into the compress library in the next version, instead of the way of the pod reference, which will significantly reduce the size of the library, but this will not be able to use the latest version at any time.

**Comment by CaiJingLong** [comment]
Try use version 0.6.2.

**Comment by Tonigt** [comment]
thanks very much, it work for my problem which version 0.62




------------------ 原始邮件 ------------------
发件人: "Caijinglong"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 晚上6:42
收件人: "OpenFlutter/flutter_image_compress"<flutter_image_compress@noreply.github.com>;
抄送: "lonely"<1984701289@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [OpenFlutter/flutter_image_compress] pod installSYPictureMetadata stuck (#66)




Closed #66.
